"""Create initial tables

Revision ID: 16488d0b2b0a
Revises: 88c5dcd7a400
Create Date: 2025-01-08 17:39:42.206724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16488d0b2b0a'
down_revision: Union[str, None] = '88c5dcd7a400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monthly_totals_id', table_name='monthly_totals')
    op.drop_index('ix_monthly_totals_month', table_name='monthly_totals')
    op.drop_index('ix_monthly_totals_plan_type', table_name='monthly_totals')
    op.drop_index('ix_monthly_totals_year', table_name='monthly_totals')
    op.drop_table('monthly_totals')
    op.drop_index('ix_insurance_files_plan_name', table_name='insurance_files')
    op.create_index(op.f('ix_insurance_files_plan_name'), 'insurance_files', ['plan_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurance_files_plan_name'), table_name='insurance_files')
    op.create_index('ix_insurance_files_plan_name', 'insurance_files', ['plan_name'], unique=False)
    op.create_table('monthly_totals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subscriber_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='monthly_totals_pkey')
    )
    op.create_index('ix_monthly_totals_year', 'monthly_totals', ['year'], unique=False)
    op.create_index('ix_monthly_totals_plan_type', 'monthly_totals', ['plan_type'], unique=False)
    op.create_index('ix_monthly_totals_month', 'monthly_totals', ['month'], unique=False)
    op.create_index('ix_monthly_totals_id', 'monthly_totals', ['id'], unique=False)
    # ### end Alembic commands ###
