"""Initial migration

Revision ID: 88c5dcd7a400
Revises: 
Create Date: 2025-01-08 17:35:10.042121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c5dcd7a400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_files_id'), 'insurance_files', ['id'], unique=False)
    op.create_index(op.f('ix_insurance_files_month'), 'insurance_files', ['month'], unique=False)
    op.create_index(op.f('ix_insurance_files_plan_name'), 'insurance_files', ['plan_name'], unique=False)
    op.create_index(op.f('ix_insurance_files_year'), 'insurance_files', ['year'], unique=False)
    op.create_table('monthly_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_totals_id'), 'monthly_totals', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_totals_month'), 'monthly_totals', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_totals_plan_type'), 'monthly_totals', ['plan_type'], unique=False)
    op.create_index(op.f('ix_monthly_totals_year'), 'monthly_totals', ['year'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_name', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('coverage_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('coverage_dates', sa.String(), nullable=True),
    sa.Column('charge_amount', sa.Float(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('insurance_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['insurance_file_id'], ['insurance_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_month'), 'employees', ['month'], unique=False)
    op.create_index(op.f('ix_employees_plan'), 'employees', ['plan'], unique=False)
    op.create_index(op.f('ix_employees_subscriber_name'), 'employees', ['subscriber_name'], unique=False)
    op.create_index(op.f('ix_employees_year'), 'employees', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_year'), table_name='employees')
    op.drop_index(op.f('ix_employees_subscriber_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_plan'), table_name='employees')
    op.drop_index(op.f('ix_employees_month'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_monthly_totals_year'), table_name='monthly_totals')
    op.drop_index(op.f('ix_monthly_totals_plan_type'), table_name='monthly_totals')
    op.drop_index(op.f('ix_monthly_totals_month'), table_name='monthly_totals')
    op.drop_index(op.f('ix_monthly_totals_id'), table_name='monthly_totals')
    op.drop_table('monthly_totals')
    op.drop_index(op.f('ix_insurance_files_year'), table_name='insurance_files')
    op.drop_index(op.f('ix_insurance_files_plan_name'), table_name='insurance_files')
    op.drop_index(op.f('ix_insurance_files_month'), table_name='insurance_files')
    op.drop_index(op.f('ix_insurance_files_id'), table_name='insurance_files')
    op.drop_table('insurance_files')
    # ### end Alembic commands ###
